#日志级别
logging:
  level:
    root: info

spring:
  profiles:
    #指定激活哪个环境
    active: dev
  #日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#Mybatis相关配置
mybatis:
  #核心配置文件路径
  config-location: classpath:mybatis/mybatis-config.xml
  #映射配置文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
